# docker run -d --restart unless-stopped --name  audiobookshelf-v1 -p 13378:80  ghcr.io/advplyr/audiobookshelf:latest

version: "3"
services:
  audiobookshelf-v1:
    user: 0:0 
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf.v1.0
    restart: unless-stopped
    command: /bin/sh -c "set -e && ./utils/check_exist_file.sh /network/za-share/exist.md && ./utils/check_dir.sh ~/srv/jellyfin/jellyfin-media"

    volumes:
      - /home/za/srv/config:/config
      - /home/zas/srv/audiobookshelf/audiobookshelf-media/audiobooks:/audiobooks
      - /home/za/srv/audiobookshelf/audiobookshelf-media/podcasts:/podcasts
    ports:
      - 13378:80
    # networks: 
    #   - traefik-net
    # labels: 
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.audiobookshelf-v1.entrypoints=web"
    #  - "traefik.http.routers.audiobookshelf-v1.rule=Host(`za.audiobookshelf.local` )"
     


# networks:
#   traefik-net:
#     name: traefik-net
#     driver: bridge

## 
## Reference 
#
## docker compose --file <path/to/audiobookshelf.v1.0.docker-compose.yml up --build -d
