# docker build --file ./Dockerfile.postgres --tag postgres/foo-v1.0 .
# docker run -d  --name postgres-foo-v1 -p 5444:5432 postgres/foo-v1.0
#

services:
  za_postgres_container:
    container_name: za_postgres_container
    image: za/postgres/postgres:latest
    build: 
      context: .
      dockerfile: './Dockerfile.postgres'  
    ports: 
      - 5444:5432  
    networks: 
      - postgress_net

networks:
  postgress_net:
    name: postgress-net
    driver: bridge

# 
# REFERENCE
# 
# docker compose -d --file ./postgres.docker-compose.yaml up
# or
# docker compse --file ./postgres.docker-compose.yaml up --build -d