# docker build --file ./Dockerfile.postgres --tag postgres/cmh-v1.0 .
# docker run -d  --name za_postgres_container -p 5444:5432 postgres/cmh-v1.0
#
version: '3'
services:
  postgres:
    container_name: za_postgres_container
    image: za/postgres/postgres:latest
    build: 
      context: .
      dockerfile: './Dockerfile.postgres'  
    ports: 
      - 5444:5432  
    networks: 
      - foo_net

networks:
  foo_net:
    name: foo_net
    driver: bridge

# 
# REFERENCE
# 
# docker compose -d --file ./postgres.docker-compose.yaml up
# 