version: "3"
services: 
    seq: 
        container_name: seq-dev
        image: datalust/seq:latest
        restart: unless-stopped
        ports: 
            - "5341:80"
        volumes: 
            - "seq-data-dev:/data"
        environment: 
            - ACCEPT_EULA=y

volumes: 
    seq-data-dev:
