version: '3'
services:
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /dev/certs:/cert
      - ./portainer.crt.pem:/etc/docker/certs.d/localhost/portainer.crt.pem
      - ./portainer.key.:/etc/docker/certs.d/localhost/portainer.key.pem
    ports:
      - 9001:9001
    # command: --ssl --sslcert /portainer.crt.pem --sslkey /portainer.key.pem
  ## 
  ## Docker command for ref
  ## 
# docker run -d \
#   -p 9001:9001 \
#   --name portainer_agent \
#   --restart=always \
#   -v /var/run/docker.sock:/var/run/docker.sock \
#   -v /var/lib/docker/volumes:/var/lib/docker/volumes \
#   portainer/agent:2.17.1

#   command: -H unix:///var/run/docker.sock --ssl --sslcert /certs/portainer.crt --sslkey /certs/portainer.key

  ### 
  ## Docker compose command ref 
  ## docker compose --file portainer-agent.docker-compose.yml up --build -d
