# docker-compose.yml
version: '3'

services:
  woodpecker-db:
    container_name: woodpeckerci-db
    platform: linux
    restart: unless-stopped
    image: postgres:12.0-alpine
    env_file: .env.production
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=true

    volumes:
      - woodpecker-data:/var/lib/postgresql/data
    ports:
      - 5444:5432
        #    networks: 
        #  - woodpeckerci-net



volumes:
  woodpecker-data:

# networks:
#  woodpeckerci-net:
#    name: woodpeckerci-net
#    driver: bridge

##
## REFERENCE
##
#
## generate secret 
#
# `openssl rand -hex 32` 
#
