# docker-compose.yml
version: '3'

services:
  woodpecker-server:
    env_file: 
      - .env.woodpecker.prod
    container_name: ${DOCKER_CONTAINER_NAME}
    image: woodpeckerci/woodpecker-server:next
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    ports:
      - ${WOODPECKER_PORT}:8000
    environment:
      - WOODPECKER_LOG_LEVEL=trace
      - WOODPECKER_DEBUG_PRETTY=true
      - WOODPECKER_DEBUG_NOCOLOR=false  
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_DATABASE_DRIVER=postgres
      - WOODPECKER_CALLBACK_URL=
      - WOODPECKER_DATABASE_DATASOURCE=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}?sslmode=disable
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT=ffcd2a147307c0dcac05
      - WOODPECKER_GITHUB_SECRET=${WOODPECKER_GITHUB_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_GITHUB_SECRET}
      - WOODPECKER_GITHUB_SKIP_VERIFY=true
    networks:
      - woodpeckerci-net
    depends_on:
      - woodpecker-db

  woodpecker-agent:
    env_file:
      - .env.woodpecker.prod
    container_name: woodpeckerci_agent_1
    image: woodpeckerci/woodpecker-agent:next
    command: agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
    networks:
      - woodpeckerci-net
    depends_on:
      - woodpecker-dbr
      - woodpecker-server

  woodpecker-db:
    container_name: woodpeckerci-db
    platform: linux
    restart: unless-stopped
    image: postgres:14
    env_file:
      - .env.woodpecker.prod
    environment: 
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust 
    volumes:
      - woodpecker-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks: 
      - woodpeckerci-net



volumes:
  woodpecker-server-data:
  woodpecker-data:

networks:
  woodpeckerci-net:
    name: woodpeckerci-net
    driver: bridge

##
## REFERENCE
##
#
## generate secret 
#
# `openssl rand -hex 32` 
#
#`docker compose --env-file .env.production --file woodpecker.docker-compose.yml  up -d`
#
##
## Start Service By Name
#
# `docker compose --env-file .env.production --file woodpecker.docker-compose.yml run woodpecker-db`
#
