
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/za-pi/services/ngnx-proxy-mgn/data:/data
      - /home/za-pi/services/ngnx-proxy-mgn/letsencrypt:/etc/letsencrypt
      
