# docker run -d --restart unless-stopped --name jellyfin -v ~/srv/jellyfin/config:/config -v ~/srv/jellyfin/cache:/cache -v /network/za-media:/media -p 8096:8096  jellyfin/jellyfin:latest

version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    command: /bin/sh -c "set -e &&  ./utils/check_exist_file.sh /network/za-share/exist.md && ./utils/check_dir.sh ~/srv/jellyfin/jellyfin-media"
    volumes:
      - /home/za/srv/jellyfin/cache:/cache
      - /home/za/srv/jellyfin/jellyfin-media:/media
      - /home/za/srv/jellyfin/config:/config
    ports:
      - 8096:8096
    healthcheck:
      test: curl --fail http://localhost:8096/
      interval: 5s
      timeout: 5s
      retries: 10
    

## docker compose --file ./jellyfin.docker-compose.yml up -d
## docker compose --file ./jellyfin.docker-compose.yml up --build -d
